### ISSUE TITLE
Carrierwave's cache_id being mistaken for guid when not uploaded directly.

### ISSUE THREAD

**Issue by nddeluca** [dwilkie/carrierwave_direct#101]
When using an uploader that uses carrierwave_direct, uploads that are not done directly mistakenly use carrierwaves temporary cache_id as part of the filename.  This gives inconsistent url's between files that are directly uploaded and those that are not.

Files should be able to be directly uploaded by the user or programmatically uploaded by the server without any change in url behavior.

**Comment by kevinc** [comment]
@nddeluca sorry to resurrect an old issue, but is there anything I can do on my side to get around this? I'm running into this also

**Comment by p8** [comment]
@kevinc This should be fixed with the following https://github.com/dwilkie/carrierwave_direct/pull/198

**Comment by kevinc** [comment]
thanks @p8! just found that and adding it to my codebase until v0.0.16 is out.

**Comment by p8** [comment]
Great! Let us know if it solves this issue.

**Comment by kevinc** [comment]
adding this in addition to https://github.com/nddeluca/carrierwave_direct/pull/1 seems to have fixed my issue

**Comment by kevinc** [comment]
looks like i spoke too soon @p8 . i'm still having the issues where it's doubling up a section of the URL.

I've gone down the road of pointing my Gemfile at the latest commit and the problem still persists, similar to:
https://github.com/dwilkie/carrierwave_direct/pull/160
https://github.com/dwilkie/carrierwave_direct/issues/118
